### PR TITLE
Restructured timetable parser class and improved error handling

### LINKED ISSUE #183: [PE-D] Error handling when invalid input was typed for add activity, similar to issue #6
Can consider catching more on these errors as mentioned

Wrong date format:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: poonchuanan/ped#7

### LINKED ISSUE #190: Bug with 12pm/12am
Class adding has error when adding 12-related number

### LINKED ISSUE #191: Timetable invalid command message is outdated
image

It should be replaced by "add activity"

### PR DESCRIPTION
**Pull request by slightlyharp**
Fix #183 
Fix #190 
Fix #191

### CODE REVIEW

File: src/main/java/timetable/TimeTableCommand.java [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+        for (Event event: eventList.events) {
+            for (Duration period: event.periods) {
+                if ((period.timeSlot.contains(now) || period.timeSlot.contains(now + 100)
+                        || period.timeSlot.contains(now + 200))
+                        && period.startDateTime.toLocalDate().equals(todayDate)) {
+                    System.out.print(event.linkOrVenue + "|" + event.name + "\n");
+                }
+            }
+        }
+    }
```
Comment (luziyi9898) [inline src/main/java/timetable/TimeTableCommand.java:187]: Some parts of the code are still too deeply nested, and it would be good to apply better SLAP to it. But if it's unavoidable then just let it be i guess.

**Review by luziyi9898 — APPROVED** [review]
Good to see that the package is a lot neater!
